/*
Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted,free of charge,to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use,reproduce,display,distribute,
execute,and transmit the Software,and to prepare derivative works of the
Software,and to permit third-parties to whom the Software is furnished to
do so,all subject to the following:

The copyright notices in the Software and this entire statement,including
the above license grant,this restriction and the following disclaimer,
must be included in all copies of the Software,in whole or in part,and
all derivative works of the Software,unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND,EXPRESS OR
IMPLIED,INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE,TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE,
ARISING FROM,OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module derelict.mono.types;

private
{
	import core.stdc.config;
	import core.stdc.stdint;
	import core.stdc.stdlib;
	import derelict.util.system;
}

// utils/mono-publib.h
alias mono_bool = int;
alias mono_byte = ubyte;
alias mono_unichar2 = wchar;
alias mono_unichar4 = dchar;

extern (C)
{
	alias MonoFunc = void function(void* data, void* user_data) nothrow;
	alias MonoHFunc = void function(void* key, void* value, void* user_data) nothrow;
}

enum MONO_ALLOCATOR_VTABLE_VERSION = 1;
struct MonoAllocatorVTable
{
	int version_;
	typeof(&.malloc) malloc;
	typeof(&.realloc) realloc;
	typeof(&.free) free;
	typeof(&.calloc) calloc;
}

static if (Derelict_OS_Linux)
	enum MONO_ZERO_LEN_ARRAY = 0;
else
	enum MONO_ZERO_LEN_ARRAY = 1;
